### ISSUE TITLE
can't find module communitysdk

### ISSUE THREAD

**Issue by kciszewski** [KanoComputing/community-sdk#11] opened 2018-10-28 22:32 UTC
I'm using the mu editor, trying to run a one of the routines in the sdk.  I keep getting a "no module communitysdk" message.  Where should I put the sdk relative to the mu editor's directories?

**Comment by murilopolese** [comment] 2018-10-29 10:01
Hey, @kciszewski! 

This is an excellent question and I'll definitely add details on that to the documentation! Thanks for asking it!

The `communitysdk` is not yet available to be installed as a global module so you must save/run your script on a folder that contains the downloaded `communitysdk`.

For example, when you download and unzip the `community-sdk-0.1.0-python` you will see there is a folder inside it called `communitysdk`. The example files will run successfully because they are "next to" this folder. 

If you copy this `communitysdk` to your `mu_code` folder, all your scripts inside `mu_code` should also be able to import the module.

I hope that answers you question. Let me know if you still have problems!

**Comment by kciszewski** [comment] 2018-10-29 22:34
Either I didn't do this right, or it doesn't work.


Attached are screen shots of two locations from which I called example_pixel_kit_stream
 and got the result shown in the third screen shot.




--------------------------------------------
On Mon, 10/29/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Monday, October 29, 2018, 5:02 AM
 
 Hey, @kciszewski!
 This is an excellent question and I'll definitely add
 details on that to the documentation! Thanks for asking
 it!
 The communitysdk is not yet available to be
 installed as a global module so you must save/run your
 script on a folder that contains the downloaded
 communitysdk.
 For example, when you download and unzip the
 community-sdk-0.1.0-python you will see there
 is a folder inside it called communitysdk. The
 example files will run successfully because they are
 "next to" this folder.
 If you copy this communitysdk to your
 mu_code folder, all your scripts inside
 mu_code should also be able to import the
 module.
 I hope that answers you question. Let me know if you
 still have problems!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment] 2018-10-29 22:59
Hey, @kciszewski ! Unfortunately I haven't got your attachments. Could you maybe upload it somewhere and send the link? Or maybe paste the full error from Mu Editor?

From what you are writing I'm sure there is a problem somewhere in the library or a detail you might be missing and that is normal. This is meant to be a learning experience both ways :)

Just to make sure, have you followed this steps?

1. Download the latest Python SDK release [here](https://github.com/KanoComputing/community-sdk/releases)
1. Unzip the folder on a folder you can find easily
1. Connect your Pixel Kit to your computer and make sure it's on
1. Open Mu Editor and switch to Python 3 mode
1. Load `example_pixel_kit_stream_frame.py` from the unziped folder
1. Press the "Run" button on the toolbar

What does the REPL prints?

**Comment by kciszewski** [comment] 2018-10-29 23:40
Here's a pdf
--------------------------------------------
On Mon, 10/29/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Monday, October 29, 2018, 5:59 PM
 
 Hey, @kciszewski !
 Unfortunately I haven't got your attachments. Could you
 maybe upload it somewhere and send the link? Or maybe paste
 the full error from Mu Editor?
 From what you are writing I'm sure there is a problem
 somewhere in the library or a detail you might be missing
 and that is normal. This is meant to be a learning
 experience both ways :)
 Just to make sure, have you followed this steps?
 
 Download the latest Python SDK release here
 Unzip the folder on a folder you can find easily
 Connect your Pixel Kit to your computer and make sure
 it's on
 Open Mu Editor and switch to Python 3 mode
 Load example_pixel_kit_stream_frame.py from
 the unziped folder
 Press the "Run" button on the toolbar
 
 What does the REPL prints?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment] 2018-10-29 23:49
Hey, @kciszewski !

Yet again, I couldn't get your attachments. You are probably replying this via email and even if you do attach things to your email response, they don't get to the [Github issues](https://github.com/KanoComputing/community-sdk/issues/11) where this conversation is being stored and displayed.

Could you maybe host this PDF/images somewhere else or just copy and paste the error instead?

If you have images you could potentially upload them to https://imgur.com/ for example (make sure there is no personal information on your screenshots ;) )

Or perhaps if it's a PDF you want to store it somewhere safe and send the link?

**Comment by kciszewski** [comment] 2018-10-30 01:27
Go to https://kciszewski.wordpress.com/2013/07/22/2/   and click on "It doesn't work''
--------------------------------------------
On Mon, 10/29/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Monday, October 29, 2018, 6:49 PM
 
 Hey, @kciszewski !
 Yet again, I couldn't get your attachments. You are
 probably replying this via email and even if you do attach
 things to your email response, they don't get to the Github
 issues where this conversation is being stored and
 displayed.
 Could you maybe host this PDF/images somewhere else or
 just copy and paste the error instead?
 If you have images you could potentially upload them to
 https://imgur.com/ for example
 (make sure there is no personal information on your
 screenshots ;) )
 Or perhaps if it's a PDF you want to store it
 somewhere safe and send the link?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment] 2018-10-31 11:16
I see your problem! Thanks you for the perseverance with the attachments :)

It seems that is a specific Windows thing related to the `PYTHONPATH`, an environment variable that tells the OS where to find modules. Thank you very much for finding this out! We'll definitely look into how to solve this once and for all.

Meanwhile, I believe you will have to add the folder where `communitysdk` is to your `PYTHONPATH`. There are several ways to do it. Here are a few entries I found on StackOverflow:

- https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows#4855685
- https://stackoverflow.com/questions/34145552/module-not-found-but-has-init-py
- https://stackoverflow.com/questions/19917492/how-to-use-pythonpath

And scenario 2 on this blog post:

https://www.daveoncode.com/2017/03/07/how-to-solve-python-modulenotfound-no-module-named-import-error/

Thank you again for writing us and I hope this helps. Let us know if it fixes your problem and how did you fix so we can add to the documentation :)

**Comment by murilopolese** [comment] 2018-11-02 09:30
Hey, @kciszewski ! Did you have any luck solving this issue? I'm very curious to understand this issue as I'm not able to reproduce it on my Windows machine. Your feedback means a lot for us!

**Comment by kciszewski** [comment] 2018-11-02 17:18
No.  The Mu editor was self installed in C:\program files, and mu_code was self installed at C:\Users\Ken\mu_code. I put the unzipped communitysdk in C:\Users\Ken\mu-code, which seemed to be the right place.

I set up PYTHONPATH=C:\Users\Ken\mu_code.

I still get the same error.

I'm running Windows 7 on a Dell Inspiron 15.

How is your Windows machine set up?
--------------------------------------------
On Fri, 11/2/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Friday, November 2, 2018, 4:30 AM
 
 Hey, @kciszewski ! Did
 you have any luck solving this issue? I'm very curious
 to understand this issue as I'm not able to reproduce it
 on my Windows machine. Your feedback means a lot for us!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by kciszewski** [comment] 2018-11-06 01:22
Are you sure the SDK is correct?  Somehow it doesn't look right to me.
--------------------------------------------
On Fri, 11/2/18, Kenneth Ciszewski <kenski@swbell.net> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <reply@reply.github.com>
 Date: Friday, November 2, 2018, 11:18 AM
 
 No.  The Mu editor was self installed in
 C:\program files, and mu_code was self installed at
 C:\Users\Ken\mu_code. I put the unzipped communitysdk in
 C:\Users\Ken\mu-code, which seemed to be the right place.
 
 I set up
 PYTHONPATH=C:\Users\Ken\mu_code.
 
 I still get the same error.
 
 I'm running Windows 7 on a Dell
 Inspiron 15.
 
 How is your Windows machine set up?
 --------------------------------------------
 On Fri, 11/2/18, Murilo Polese <notifications@github.com>
 wrote:
 
  Subject: Re:
 [KanoComputing/community-sdk] can't find module communitysdk
 (#11)
  To: "KanoComputing/community-sdk"
 <community-sdk@noreply.github.com>
  Cc: "kciszewski" <kenski@swbell.net>,
 "Mention" <mention@noreply.github.com>
  Date: Friday, November 2, 2018, 4:30
 AM
  
  Hey, @kciszewski ! Did
  you have any luck solving this issue?
 I'm very curious
  to understand this issue as I'm not
 able to reproduce it
  on my Windows machine. Your feedback
 means a lot for us!
  
  —
  You are receiving this because you
 were mentioned.
  Reply to this email directly, view
  it on GitHub, or mute
  the thread.

**Comment by kciszewski** [comment] 2018-11-06 04:11
I tried setting the PYTHONPATH, but no luck.  I am using Windows 7 on a Dell Inspiron.  Someone surely knows what it takes to get this running.  Is it possible the SDK simply isn't right or complete?

**Comment by murilopolese** [comment] 2018-11-06 10:42
Hey, @kciszewski !

My setups are:
- Ubuntu 18.04.1 on a Dell XPS 13
- Windows 10 (MSEdge image) on VirtualBox
- OSX High Sierra on a MacBook
- KanoOS on Raspberry Py 3

I'm pretty sure the problem is not on the SDK itself but you can consider your difficulty a problem on the documentation for Windows, which it seems to be the only platform this problem actually occur. I will definitely be working on improving this on the next days.

In fact, after reading more about the subject I realized Mu Editor uses a completely separated Python environment so setting the system path won't really affect the Python environment it runs. Therefore adding the following lines (as described in one of the links I sent above) on top of your script will solve your problem:

```python
import sys,os
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
```
As you can see on [this screenshot](https://imgur.com/p0Sn8cf), this seems to work.

This issue totally went without proper attention but now it will be properly addressed with documentation and perhaps a specific example for Windows. Let me know if this works for you and thanks again for the report!

**Comment by kciszewski** [comment] 2018-11-06 17:34
Thanks!  That seems to work.

I have a question about running 

example_pixel_kit_status.py.

The result I got was 

Traceback (most recent call last):
  File "c:\users\ken\mu_code\example_pixel_kit_get_status.py", line 17, in <module>
    battery_status = pk.get_battery_status()
  File "c:\users\ken\mu_code\communitysdk\retailpixelkit.py", line 49, in get_battery_status
    return self.rpc_request('battery-status', [])
  File "c:\users\ken\mu_code\communitysdk\rpcclient.py", line 76, in rpc_request
    self.loop.run_until_complete(tasks)
  File "asyncio\base_events.py", line 467, in run_until_complete
  File "c:\users

---------- FINISHED ----------
exit code: 2 status: 0


I'm not sure this is the correct result.
--------------------------------------------
On Tue, 11/6/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] can't find module communitysdk (#11)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, November 6, 2018, 4:43 AM
 
 Hey, @kciszewski !
 My setups are:
 
 Ubuntu 18.04.1 on a Dell XPS 13
 Windows 10 (MSEdge image) on VirtualBox
 OSX High Sierra on a MacBook
 KanoOS on Raspberry Py 3
 
 I'm pretty sure the problem is not on the SDK itself
 but you can consider your difficulty a problem on the
 documentation for Windows, which it seems to be the only
 platform this problem actually occur. I will definitely be
 working on improving this on the next days.
 In fact, after reading more about the subject I realized
 Mu Editor uses a completely separated Python environment so
 setting the system path won't really affect the Python
 environment it runs. Therefore adding the following lines
 (as described in one of the links I sent above) on top of
 your script will solve your problem:
 import sys,os
 sys.path.append(os.path.abspath(os.path.dirname(__file__)))
 As you can see on this screenshot, this
 seems to work.
 This issue totally went without proper attention but now
 it will be properly addressed with documentation and perhaps
 a specific example for Windows. Let me know if this works
 for you and thanks again for the report!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment] 2018-11-06 23:13
Hey, @kciszewski!

I'm really happy to hear that solved the issue. I'll definitely add [this lines of code to the docs](https://github.com/KanoComputing/community-sdk/wiki/Documentation-and-Examples#note-for-windows-users)! Win for Windows users!

Regarding your other issue, the error message you sent seems to be truncated just on the most important part... I noticed that Mu sometimes truncates it so, if I could ask a favor, can you run it again and see if you get the full Traceback?

By the way, the Traceback will, usually tell you exactly the line that is giving you this issue and it's very likely will explain the bug!

```python
File "c:\users\ken\mu_code\communitysdk\rpcclient.py", line 76, in rpc_request
    self.loop.run_until_complete(tasks)
```

This is the last file inside the SDK where I see the issue and if we look at the code it will show that the `tasks` are:

```python
tasks = asyncio.gather(
  self.send(request_str),
  self.wait_for_response(id)
)
```

Both methods `send` and `wait_for_response` are above in this file and I will assume it's either a connection problem, a serial write, a timeout or an unexpected response from the serial port... But it's hard to tell with the truncated Traceback.

**Comment by murilopolese** [comment] 2018-11-06 23:48
It seems that the main problem of this issue was fixed and what you are struggling now looks more with this other issue:

https://github.com/KanoComputing/community-sdk/issues/10

So for matter of helping me to keep it organised, would you mind to close this issue and move the discussion about it to the issue above? :)

**Closed as completed** 2018-11-12 11:03 UTC
Labels: bug, question, python
